version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ${GCP_IMAGE}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todaystock
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: