spring:
  application:
    name: todaystock
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      logging.level.org.hibernate.SQL: debug
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    fail-on-missing-locations: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    vertex:
      ai:
        gemini:
          project-id: todaystock
          location: asia-northeast3
          chat:
            options:
              model: vertex-pro-vision
              temperature: 0.5

jwt:
  secret: ${JWT_SECRET}


naver:
  api:
    client:
      id: ${NAVER_CLIENT_ID}
      secret: ${NAVER_CLIENT_SECRET}

sql:
  init:
    mode: always

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace