spring:
  application:
    name: todaystock
  datasource:
    url: jdbc:postgresql://localhost:5432/todaystock
    username: ilpyo
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      logging.level.org.hibernate.SQL: debug
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

sql:
  init:
    mode: always

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace