name: Build and Deploy (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: build -x test

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_REGISTRY_ADMIN_SECRET }}

      - name: set up cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          version: 'latest'

      - name: docker-auth
        run: gcloud auth configure-docker ${{ secrets.GCP_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_REGISTRY_ADMIN_SECRET }}

      - name: Pull and Tag Docker Image, then Deploy
        run: |
          gcloud compute ssh todaystock-instance --zone asia-northeast3-a --command "
            docker pull ${ secrets.GCP_IMAGE_TAG } &&
            sudo docker run -d -p 80:80 ${ secrets.GCP_IMAGE_TAG }
          "