name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: build -x test

      - name: Set vars
        run: echo "IMAGE_TAG=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.GITHUB_REPOSITORY_BRANCH }}/${{ env.IMAGE }}" >> $GITHUB_ENV

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_REGISTRY_ADMIN_SECRET }}

      - name: set up cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT }}
          version: 'latest'

      - name: docker-auth
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}

env:
  GCP_REGION: asia-northeast3
  PROJECT: gemstock-431908
  GITHUB_REPOSITORY_BRANCH: todaystock-registry-docker
  IMAGE: todaystock