name: Build and Deploy (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: clean build -x test --no-build-cache

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_REGISTRY_ADMIN_SECRET }}

      - name: set up cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          version: 'latest'

      - name: docker-auth
        run: gcloud auth configure-docker ${{ secrets.GCP_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_IMAGE_TAG }}
          no-cache: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_REGISTRY_ADMIN_SECRET }}

      - name: Pull and Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.GCP_SSH_HOST }}
          username: ${{ secrets.GCP_SSH_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          script_stop: true
          script: |
            > .env
            echo "${{ env.ENV }}" >> .env
            docker ps -aq | xargs -r docker rm -f
            docker run -d --restart=always --name todaystock --env-file .env -p 8080:8080 ${{ secrets.GCP_IMAGE_TAG }}